#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob0
#PBS -o myjob.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M jmd070@latech.edu
work="/home/johnmdo/Lab2"
XFILE="lab2_4"
cd $work
echo "MPI run with 4 processes."
mpirun -np 4 -machinefile $PBS_NODEFILE ./$XFILE
echo "MPI run with 8 processes."
mpirun -np 8 -machinefile $PBS_NODEFILE ./$XFILE

