#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob0
#PBS -o myjob.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M jmd070@latech.edu
work="/home/johnmdo/Lab2"
CFILE="lab2_1a"
cd $work
mpirun -np 20 -machinefile $PBS_NODEFILE ./$CFILE

